name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn clean_build

    - name: Deploy
      run: yarn deploy