name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      id: cache
      with:
        path: node_modules 
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
  
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Postinstall Dependencies
      if: steps.cache.outputs.cache-hit == 'true'
      run: yarn postinstall

    - name: Build
      run: yarn clean_build

    - name: Deploy
      env:
        NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
      run: yarn deploy