name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: List directories
      run: ls -al packages/client

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules 
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-node_modules
  
    - name: Cache client web modules
      uses: actions/cache@v1
      with:
        path: packages/client/web_modules 
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-client_web_modules
  
    - name: Cache client node modules
      id: node_modules
      uses: actions/cache@v1
      with:
        path: packages/client/node_modules 
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-client_node_modules
  
    - name: List directories after cache checks
      run: ls -al packages/client

    - name: Install Dependencies
      if: steps.node_modules.outputs.cache-hit != 'true'
      run: yarn install

    - name: List directories after install dependencies
      run: ls -al packages/client

    - name: Build
      run: yarn clean_build

    - name: Deploy
      env:
        NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
      run: yarn deploy